parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(RETRAINRD_DATABASE_URL): ''

doctrine:
    dbal:
        driver: 'pdo_pgsql'
        server_version: '9.6'
        url: '%env(resolve:RETRAINRD_DATABASE_URL)%'
        mapping_types:
            point: point
        types:
            point: App\Doctrine\DBAL\Type\PointType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
