easy_admin:
    site_name: 'Administration'

    design:
        menu:
            - label: 'admin.menu.home'
              icon: 'home'
              route: 'app_user_home'

            - label: 'admin.menu.permissions'
              icon: 'users'
              children:
                  - { entity: 'UserAdmin', icon: 'user-secret', label: 'admin.menu.user_admin'  }
                  - { entity: 'User', icon: 'user', label: 'admin.menu.user' }

            - label: 'admin.menu.parameters'
              icon: 'sliders'
              children:
                  - { entity: 'Stop', icon: 'home', label: 'admin.menu.stop' }


    show:
        actions: ['-delete']
    edit:
        actions: ['-delete']
    list:
        max_results: 25
        actions:
            - { name: 'show', icon: 'search', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: '-delete' }


    entities:
        Stop:
            class: App\Entity\Stop
            label: 'admin.entities.stop'
            disabled_actions: ['new']
            list:
                sort: ['id', 'ASC']
                fields:
                    - { property: 'id', label: 'admin.stop.fields.id' }
                    - { property: 'code', label: 'admin.stop.fields.code' }
                    - { property: 'name', label: 'admin.stop.fields.name' }
                    - { property: 'label', label: 'admin.stop.fields.label' }
                    - { property: 'latitude', label: 'admin.stop.fields.latitude' }
                    - { property: 'longitude', label: 'admin.stop.fields.longitude' }
            show:
                fields:
                    - { property: 'id', label: 'admin.stop.fields.id' }
                    - { property: 'code', label: 'admin.stop.fields.code' }
                    - { property: 'name', label: 'admin.stop.fields.name' }
                    - { property: 'label', label: 'admin.stop.fields.label' }
                    - { property: 'latitude', label: 'admin.stop.fields.latitude' }
                    - { property: 'longitude', label: 'admin.stop.fields.longitude' }
            form:
                fields:
                    - { property: 'code', label: 'admin.stop.fields.code' }
                    - { property: 'name', label: 'admin.stop.fields.name' }
                    - { property: 'label', label: 'admin.stop.fields.label' }
                    - { property: 'latitude', label: 'admin.stop.fields.latitude', type: 'number', type_options: { scale: 6 } }
                    - { property: 'longitude', label: 'admin.stop.fields.longitude', type: 'number', type_options: { scale: 6 } }


        UserAdmin:
            class: App\Entity\User
            title: 'admin.entities.user_admin'
            list:
                sort: ['id', 'ASC']
                dql_filter: "entity.roles LIKE '%%ROLE_ADMIN%%'"
                fields:
                    - { property: 'id', label: 'admin.user_admin.fields.id' }
                    - { property: 'email', label: 'admin.user_admin.fields.email' }
                    - { property: 'firstName', label: 'admin.user_admin.fields.first_name' }
                    - { property: 'lastName', label: 'admin.user_admin.fields.last_name' }
                    - { property: 'superAdmin', type: 'boolean', label: 'admin.user_admin.fields.super_admin' }
                    - { property: 'enabled', type: 'boolean', label: 'admin.user_admin.fields.enabled' }
            show:
                fields:
                    - { property: 'id', label: 'admin.user_admin.fields.id' }
                    - { property: 'email', label: 'admin.user_admin.fields.email' }
                    - { property: 'firstName', label: 'admin.user_admin.fields.first_name' }
                    - { property: 'lastName', label: 'admin.user_admin.fields.last_name' }
                    - { property: 'superAdmin', type: 'boolean', label: 'admin.user_admin.fields.super_admin' }
                    - { property: 'enabled', label: 'admin.user_admin.fields.enabled' }
            new:
                fields:
                    - { property: 'email', label: 'admin.user_admin.fields.email' }
                    - { property: 'password', label: 'admin.user_admin.fields.password' }
                    - { property: 'firstName', label: 'admin.user_admin.fields.first_name' }
                    - { property: 'lastName', label: 'admin.user_admin.fields.last_name' }
                    - { property: 'superAdmin', type: 'checkbox', label: 'admin.user_admin.fields.super_admin' }
                    - { property: 'enabled', label: 'admin.user_admin.fields.enabled' }
                form_options: { validation_groups: ['admin_create'] }
            edit:
                fields:
                    - { property: 'email', , type_options: { attr: { readonly: true } }, label: 'admin.user_admin.fields.email' }
                    - { property: 'firstName', label: 'admin.user_admin.fields.first_name' }
                    - { property: 'lastName', label: 'admin.user_admin.fields.last_name' }
                    - { property: 'superAdmin', type: 'checkbox', label: 'admin.user_admin.fields.super_admin' }
                    - { property: 'enabled', label: 'admin.user_admin.fields.enabled' }
                form_options: { validation_groups: ['admin_edit'] }


        User:
            class: App\Entity\User
            label: 'admin.entities.user'
            disabled_actions: ['new']
            list:
                sort: ['id', 'ASC']
                dql_filter: "entity.roles NOT LIKE '%%ROLE_ADMIN%%'"
                actions:
                    - { name: 'app_simple_registration_send', icon: 'refresh', label: '', type: 'route' }
                fields:
                    - { property: 'id', label: 'admin.user.fields.id' }
                    - { property: 'email', label: 'admin.user.fields.email' }
                    - { property: 'firstName', label: 'admin.user.fields.first_name' }
                    - { property: 'lastName', label: 'admin.user.fields.last_name' }
                    - { property: 'enabled', type: 'boolean', label: 'admin.user.fields.enabled' }
                    - { property: 'titleRegistrationState', label: 'admin.user.fields.registration_state' }
            form:
                fields:
                    - { property: 'email', type_options: { attr: { readonly: true } }, label: 'admin.user.fields.email' }
                    - { property: 'firstName', label: 'admin.user.fields.first_name' }
                    - { property: 'lastName', label: 'admin.user.fields.last_name' }
                    - { property: 'enabled', label: 'admin.user.fields.enabled' }
                form_options: { validation_groups: ['user_edit'] }
