easy_admin:
    site_name: 'Administration'

    design:
        menu:
            - { entity: 'Stop', icon: 'home' }

    formats:
        number: '%.2f'

    show:
        actions: ['-delete']
    edit:
        actions: ['-delete']
    list:
        max_results: 25
        actions:
            - { name: 'show', icon: 'search', label: '' }
            - { name: 'edit', icon: 'pencil', label: '' }
            - { name: '-delete' }

    entities:
        Stop:
            class: App\Entity\Stop
            disabled_actions: ['new']
            list:
                sort: ['id', 'ASC']
