framework:
    secret: '%env(APP_RETRAINRD_SECRET)%'
    #csrf_protection: ~
    #http_method_override: true

    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: 'retrainrd'

    #esi: ~
    #fragments: ~
    php_errors:
        log: true
