old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(resolve:RETRAINRD_RABBITMQ_URL)%'
            lazy: false
            connection_timeout: 3
            read_write_timeout: 3
    producers:
        registration:
            connection: default
            exchange_options: {name: 'registration', type: direct}
        password_lost:
            connection: default
            exchange_options: {name: 'password_lost', type: direct}
        mail_update_account:
            connection: default
            exchange_options: {name: 'mail_update_account', type: direct}
        mail_enable_account:
            connection: default
            exchange_options: {name: 'mail_enable_account', type: direct}
        mail_disable_account:
            connection: default
            exchange_options: {name: 'mail_disable_account', type: direct}
    consumers:
        registration:
            connection: default
            exchange_options: {name: 'registration', type: direct}
            queue_options: {name: 'registration'}
            callback: App\Consumer\RegistrationConsumer
        password_lost:
            connection: default
            exchange_options: {name: 'password_lost', type: direct}
            queue_options: {name: 'password_lost'}
            callback: App\Consumer\PasswordLostConsumer
        mail_update_account:
            connection: default
            exchange_options: {name: 'mail_update_account', type: direct}
            queue_options: {name: 'mail_update_account'}
            callback: App\Consumer\MailUpdateAccountConsumer
        mail_enable_account:
            connection: default
            exchange_options: {name: 'mail_enable_account', type: direct}
            queue_options: {name: 'mail_enable_account'}
            callback: App\Consumer\MailEnableAccountConsumer
        mail_disable_account:
            connection: default
            exchange_options: {name: 'mail_disable_account', type: direct}
            queue_options: {name: 'mail_disable_account'}
            callback: App\Consumer\MailDisableAccountConsumer
