security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        simple-registration:
            pattern: ^/(registration|active/.*)
            anonymous: true

        account:
            pattern: ^/password-lost$
            anonymous: true

        home:
            pattern: ^/$
            anonymous: true

        connection:
            pattern: ^/connect(/.*)?
            anonymous: true

        app:
            provider: users
            pattern: ^/
            form_login:
                login_path: app_connection
                check_path: app_connection_check
                success_handler: App\Handler\AuthenticationSuccessHandler
            logout:
                path: app_disconnection
                target: app_connection
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
