version: '2'

networks:
    retrainrd:
        external: true

services:
    app:
        build: docker/app
        working_dir: /var/www/app
        environment:
            XDEBUG_ENABLED: 1
        env_file:
            - .env
        networks:
            retrainrd:
                aliases:
                    - app
        volumes:
            - .:/var/www/app
            - ~/.composer:/var/www/.composer
        depends_on:
            - db

    web:
        image: nginx:1-alpine
        networks:
            retrainrd:
                aliases:
                    - web
        volumes:
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/app:ro
        expose:
            - 80
        depends_on:
            - app

    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: retrainrd
            MYSQL_PASSWORD: retrainrd
            MYSQL_DATABASE: retrainrd
        networks:
            retrainrd:
                aliases:
                    - db
        volumes:
            - ./docker/db:/usr/local/src
