controllers:
    resource: '../src/Controller/'
    type: 'annotation'

app_connection_check:
    path: '/login-check'
    methods: ['POST']

app_disconnection:
    path: '/logout'
    methods: ['GET']

