parameters:
    locale: 'fr'

    app.scnf_base_url: 'https://api.sncf.com/v1/'
    app.sncf_token: '%env(RETRAINRD_APP_SNCF_TOKEN)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $clientSNCF: '@csa_guzzle.client.sncf_api'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
